/* ==========================================================================
   Insiyab · the demo site
   ==========================================================================

   The demo is a documentation site: one page per topic, static HTML, the same
   shell on every page. It is generated rather than hand-written because the
   shell — sidebar, top bar, search, pager — is identical on ~40 pages, and
   forty hand-kept copies of one sidebar are forty chances to forget a link.

   Sources live in demo/src:

     site.mjs          this file: the page list (the one place a page is added)
     layout.html       the shell every page is poured into
     pages/<slug>.html one fragment per page — just its content

   Output is demo/<slug>.html, plain files that need no script to read. They are
   committed, so the demo works from a static host or a checkout with no build.

   Two custom tags are expanded at build time, so a page never repeats itself:

     <demo-example class="row">…live markup…</demo-example>
         renders the markup, and prints the same markup, highlighted, under it.
         `code="none"` renders without the listing.

     <demo-code lang="html|js|css|sh">…source…</demo-code>
         a listing on its own. Write the source as-is; it is escaped here.

   `level: 'simple' | 'advanced'` in NAV, or `data-level` on an <h2>/<h3>, shows that page or section in that mode only; untagged shows in both.

   Run through `node build.mjs`, which calls buildSite() after the library.
   ========================================================================== */

import { readFile, writeFile, readdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';

const DIR = 'demo';
const SRC = 'demo/src';
const MARK = '<!-- generated by build.mjs from demo/src/pages/';

/* --------------------------------------------------------------------------
   The page list. Order here is order in the sidebar and in the pager.
   `en` and `lead` are the search's keywords, carried on each sidebar link:
   `en` so an English query ("button") finds the page, the lead so a singular
   ("جدول") finds a page named in the plural ("الجداول").
   -------------------------------------------------------------------------- */

export const NAV = [
  { group: 'البداية', en: 'Getting started', pages: [
    { slug: 'index', title: 'مقدمة', en: 'Introduction', icon: 'home', hero: true },
    { slug: 'start', title: 'البدء السريع', en: 'Quick start', icon: 'rocket',
      lead: 'انسخ مجلد المكتبة إلى مشروعك، وأضف وسومها إلى الصفحة، فتكون جاهزة في دقيقة.' },
    { slug: 'javascript', level: 'advanced', title: 'جافاسكربت', en: 'JavaScript', icon: 'code',
      lead: 'السمات هي الباب، والواجهة البرمجية مخرج للطوارئ: كل ما يتحرك في المكتبة يعمل بسمة تكتبها، دون سطر جافاسكربت واحد.' },
    { slug: 'faq', title: 'أسئلة شائعة', en: 'FAQ', icon: 'help',
      lead: 'ما يسأل عنه الناس قبل أن يعتمدوا المكتبة، بأجوبة قصيرة.' }
  ] },
  { group: 'التخصيص', en: 'Customize', pages: [
    { slug: 'color', title: 'اللون والهوية', en: 'Color & branding', icon: 'palette',
      lead: 'اختر لونًا واحدًا، وتُشتق منه البقية: التدرج والظلال وحلقات التركيز وخلفية الصفحة.' },
    { slug: 'dark', title: 'الوضع الداكن', en: 'Dark mode', icon: 'moon',
      lead: 'ألوان صيغت لليل خاصة لا قُلبت عن النهار. يتبع النظام من تلقاء نفسه، ويحفظ لكل مستخدم اختياره.' },
    { slug: 'rtl', title: 'العربية والاتجاه', en: 'Arabic & RTL', icon: 'languages',
      lead: 'الكتابة من اليمين إلى اليسار أصل فيها لا إضافة: خصائص CSS المنطقية (logical properties) في كل قاعدة، فلا ملف يعكس الصفحة.' },
    { slug: 'motion', level: 'advanced', title: 'الحركة', en: 'Motion', icon: 'sparkle',
      lead: 'منحنى واحد، ودخول أهدأ من الخروج، ولا حركة تدور بلا غاية.' }
  ] },
  { group: 'التخطيط', en: 'Layout', pages: [
    { slug: 'shell', title: 'هيكل التطبيق', en: 'App shell', icon: 'layout',
      lead: 'شريط جانبي من زجاج، وشريط علوي من جزر عائمة، وهذه الصفحة نفسها مبنية بهما.' },
    { slug: 'grid', title: 'الشبكة', en: 'Grid', icon: 'grid',
      lead: 'أعمدة تنطوي وحدها كلما ضاقت الشاشة، فلا تحتاج كلاسًا لكل مقاس.' },
    { slug: 'spacing', title: 'المسافات والترتيب', en: 'Spacing & page layout', icon: 'sliders',
      lead: 'للصفحة تخطيطان: تطبيق يملأ عرضها، وعمود يتوسطها. وللمسافات سلم واحد خطوته 4 بكسل، يتبع اتجاه الصفحة.' },
    { slug: 'split', title: 'العرض المقسوم', en: 'Split view', icon: 'sidebar', fresh: true,
      lead: 'لوحان يتقاسمان العرض بخط تسحبه: مستند بجانب نموذجه، أو قائمة بجانب ما تفتحه منها.' }
  ] },
  { group: 'المحتوى', en: 'Content', pages: [
    { slug: 'typography', title: 'الخطوط والنصوص', en: 'Typography', icon: 'type',
      lead: 'ثلاثة خطوط مستضافة مع المكتبة لا يُحمل منها إلا ما تحتاجه الصفحة، وسلم للعناوين، ونص طويل لا يتجاوز تنسيقه الكلاس الذي يحمله.' },
    { slug: 'surfaces', title: 'الأسطح والألواح', en: 'Surfaces & panels', icon: 'layers',
      lead: 'الزجاج المصنفر بطبقاته الأربع، وما يبنى عليه من بطاقات وألواح.' },
    { slug: 'tables', title: 'الجداول', en: 'Tables', icon: 'table', fresh: true,
      lead: 'جدول بيانات تصطف أرقامه، ويتمرر عرضًا داخل حاويته فلا تتسع الصفحة معه.' },
    { slug: 'description', title: 'قائمة الوصف', en: 'Description list', icon: 'list', fresh: true,
      lead: 'تفاصيل سجل واحد، تسمية وقيمة: صف لكل زوج، أو أعمدة لملخص قصير.' },
    { slug: 'quote', title: 'الاقتباس والتظليل', en: 'Quote, reference & highlight', icon: 'message', fresh: true,
      lead: 'نص منقول بمصدره، وعلامة تحيل إلى مرجع، وتظليل يربط أجزاء النص بملاحظات تشرح سببها.' }
  ] },
  { group: 'النماذج', en: 'Forms', pages: [
    { slug: 'inputs', title: 'الحقول', en: 'Form controls', icon: 'edit', fresh: true,
      lead: 'حقل النص والقائمة ومربع النص الطويل، بثلاثة مقاسات، ومعها التسمية والتلميح.' },
    { slug: 'checks', title: 'الاختيار والمفاتيح', en: 'Checks & switches', icon: 'check-square',
      lead: 'مربعات ودوائر ومفاتيح وبطاقات اختيار، وتحت كل تصميم عنصر إدخال حقيقي.' },
    { slug: 'input-group', title: 'مجموعات الحقول', en: 'Input groups', icon: 'link',
      lead: 'حقل وملحقاته قطعة واحدة: وحدة قياس، أو بادئة، أو زر، أو إظهار كلمة المرور.' },
    { slug: 'pickers', title: 'أدوات الاختيار', en: 'Pickers', icon: 'calendar', fresh: true,
      lead: 'الإكمال التلقائي والتاريخ والوقت والمنزلق والعداد، أدوات لا يستغني عنها نموذج جاد.' },
    { slug: 'chips', title: 'الرقاقات والوسوم', en: 'Chips, tags & multi-select', icon: 'tag', fresh: true,
      lead: 'الرقاقات (Chips) قيم صغيرة تُزال أو تُضغط، وحقل يجمع عدة قيم: اختيار متعدد من قائمة، أو وسوم تكتبها بنفسك.' },
    { slug: 'matrix', title: 'مصفوفة الاختيار', en: 'Choice matrix', icon: 'grid', fresh: true,
      lead: 'أسئلة في صفوف تتشارك الإجابات نفسها: استبيان، أو معايير لكل مستوى منها وصف ودرجة.' },
    { slug: 'validation', title: 'التحقق', en: 'Validation', icon: 'shield',
      lead: 'تحقق المتصفح نفسه، ورسائله تحت الحقل لا في فقاعة، دون مكتبة تحقق.' }
  ] },
  { group: 'المكونات', en: 'Components', pages: [
    { slug: 'buttons', title: 'الأزرار', en: 'Buttons', icon: 'pointer',
      lead: 'ألوان وأنماط ومقاسات، وأزرار تبديل ومجموعات، وزر للإغلاق.' },
    { slug: 'accordion', title: 'الأكورديون', en: 'Accordion', icon: 'chevrons',
      lead: 'أقسام تنطوي وتنفتح، مبنية على عنصر details نفسه فتعمل بلا جافاسكربت.' },
    { slug: 'tabs', title: 'علامات التبويب', en: 'Tabs', icon: 'tabs',
      lead: 'تبويبات تبدل الألواح بالنقر وبالأسهم، في شكلين: شريط، وأزرار متلاصقة.' },
    { slug: 'stats', title: 'البطاقات الإحصائية', en: 'Stat tiles', icon: 'chart', fresh: true,
      lead: 'رقم ومعناه وأيقونة، بست نبرات وثلاثة مقاسات.' },
    { slug: 'loading', title: 'التحميل والحالة الفارغة', en: 'Loading & empty states', icon: 'loader',
      lead: 'هيكل التحميل (skeleton) ومؤشر التحميل والحالة الفارغة: ما يراه المستخدم قبل وصول البيانات، أو حين لا تصل.' },
    { slug: 'progress', title: 'التقدم', en: 'Progress', icon: 'gauge',
      lead: 'شريط تقدم على عنصر progress الأصلي، وحلقة للنسب المئوية.' },
    { slug: 'countdown', title: 'العد التنازلي والحفظ', en: 'Countdown & save status', icon: 'clock', fresh: true,
      lead: 'كم بقي من الوقت، وهل حُفظ آخر تغيير: جارٍ الحفظ، أو حُفظ، أو تعذر.' },
    { slug: 'tooltips', title: 'التلميحات', en: 'Tooltips', icon: 'message',
      lead: 'تلميح واحد يخدم الصفحة كلها من الطبقة العليا (top layer)، بسمة تضعها على العنصر.' },
    { slug: 'alerts', title: 'التنبيهات', en: 'Alerts', icon: 'alert',
      lead: 'رسالة تستقر في الصفحة بأربع نبرات، ويمكن إغلاقها.' },
    { slug: 'dialog', title: 'مربع الحوار', en: 'Dialog', icon: 'window',
      lead: 'على عنصر dialog الأصلي، فالطبقة العليا (top layer) وحبس التركيز (focus trap) والإغلاق بـ Esc كلها من المتصفح.' },
    { slug: 'drawer', title: 'الدرج', en: 'Drawer', icon: 'sidebar',
      lead: 'الدرج (Drawer) هو مربع الحوار نفسه ملتصقًا بحافة: البداية أو النهاية أو الأسفل.' },
    { slug: 'toasts', title: 'الرسائل العابرة', en: 'Toasts', icon: 'bell',
      lead: 'الرسالة العابرة (Toast) إشعار يظهر ثم يختفي وحده، بسمة على زر أو بسطر جافاسكربت.' },
    { slug: 'badges', title: 'الشارات والأرقام', en: 'Badges & numbers', icon: 'tag', fresh: true,
      lead: 'شارات للحالة وللعدد، وصور رمزية، ومبالغ وأرقام لا تضطرب في السطر العربي.' },
    { slug: 'list', title: 'القوائم', en: 'Lists', icon: 'list',
      lead: 'صفوف متتالية فيها صورة ونصان وخاتمة، ثابتة أو قابلة للنقر.' },
    { slug: 'comments', title: 'التعليقات والرسائل', en: 'Comments & messages', icon: 'inbox', fresh: true,
      lead: 'كلام الناس في سلسلة: تعليق على سجل وردود عليه، أو رسائل محادثة.' },
    { slug: 'dropdown', title: 'القوائم المنسدلة', en: 'Dropdowns', icon: 'menu-down',
      lead: 'قائمة منسدلة (dropdown) على عنصر details، تتنقل فيها بالأسهم وتغلقها بـ Esc، وفيها عناصر يمكن تحديدها.' },
    { slug: 'steps', title: 'الخطوات والمعالج', en: 'Steps & wizard', icon: 'steps', fresh: true,
      lead: 'المعالج (Wizard) نموذج مقسم إلى خطوات، لا يغادر خطوة حتى يتحقق منها.' },
    { slug: 'pagination', title: 'ترقيم الصفحات', en: 'Pagination', icon: 'pages',
      lead: 'روابط صفحات حقيقية، وأسهمها تتبع اتجاه النص.' },
    { slug: 'page-head', title: 'رأس الصفحة والمسار', en: 'Page header & breadcrumb', icon: 'route',
      lead: 'عنوان الصفحة وسطر تحته وإجراءاتها، ومسار التنقل (breadcrumb) فوقها.' }
  ] },
  { group: 'الأدوات', en: 'Utilities', pages: [
    { slug: 'utilities', title: 'الأدوات المساعدة', en: 'Utilities', icon: 'wrench',
      lead: 'كلاسات صغيرة للنص والـ flex والإظهار، تُحمل بعد المكونات كلها فتغلبها دون !important.' }
  ] },
  { group: 'الإضافات', en: 'Plugins', pages: [
    { slug: 'hijri', title: 'التقويم الهجري', en: 'Hijri calendar', icon: 'moon',
      lead: 'حقل التاريخ بالتقويم الهجري، أم القرى أو الحسابي، ومفتاح يقلبه إلى الميلادي. أما الخادم فيستلم التاريخ الميلادي كما اعتاد.' },
    { slug: 'palette', level: 'advanced', title: 'لوحة الأوامر', en: 'Command palette', icon: 'search',
      lead: 'لوحة الأوامر (Command palette) بحث واحد يصل إلى كل صفحة وكل أمر، تفتحه بـ Ctrl+K. عناصره روابط الصفحة وأزرارها نفسها، ويجمع روابط القائمة الجانبية وحده.' },
    { slug: 'otp', title: 'رمز التحقق', en: 'One-time code', icon: 'lock',
      lead: 'حقل رمز التحقق (OTP) المرسل في رسالة، لكل رقم مربع، وهو في الحقيقة حقل واحد: يُلصق فيه، ويقترحه الهاتف، ويقرؤه قارئ الشاشة.' },
    { slug: 'phone', title: 'رقم الهاتف', en: 'Phone number', icon: 'phone',
      lead: 'حقل الهاتف بدولته: يُكتب الرقم كما يكتبه أهل بلده، ويصل إلى الخادم بصيغة E.164 الدولية.' },
    { slug: 'birthdate', level: 'advanced', title: 'تاريخ الميلاد', en: 'Birth date', icon: 'calendar', fresh: true,
      lead: 'يكتبه صاحبه كما يقوله، أو يختاره بإصبعه: حقل لتاريخ الميلاد لا يقبل تاريخًا مستحيلًا، ويصل إلى الخادم بصيغة ISO.' },
    { slug: 'file', title: 'رفع الملفات', en: 'File upload', icon: 'upload',
      lead: 'اسحب الملفات إلى منطقة الإفلات فتظهر في قائمة، وتبقى في حقلها الحقيقي فتُرسل مع النموذج كما هي.' },
    { slug: 'scrollspy', level: 'advanced', title: 'تتبع القراءة', en: 'Scrollspy', icon: 'list',
      lead: 'قائمة محتويات (Scrollspy) تتبع القارئ، فتبرز رابط القسم الذي يقرؤه، في الصفحة أو في صندوق له تمريره الخاص.' },
    { slug: 'timeline', title: 'الخط الزمني', en: 'Timeline', icon: 'clock',
      lead: 'ما جرى بترتيبه: مسار طلب، أو نشاط حساب، أو تاريخ ملف، وأوقات نسبية تُكتب كما تُقال.' },
    { slug: 'tree', title: 'الشجرة', en: 'Tree', icon: 'folder',
      lead: 'قوائم متداخلة تصير شجرة: ملفات أو تصنيفات أو صلاحيات، تتنقل فيها بالأسهم، ومعها مربعات اختيار متسلسلة.' },
    { slug: 'charts', title: 'الرسوم البيانية', en: 'Charts', icon: 'chart', fresh: true,
      lead: 'أعمدة وخطوط وحلقات وتوزيعات ترسم من جدول، بألوان المكتبة واتجاه القراءة، وتبقى أرقامها مقروءة لقارئ الشاشة.' },
    { slug: 'month', title: 'تقويم الشهر', en: 'Month calendar', icon: 'calendar', fresh: true,
      lead: 'شهر على شبكة بمواعيد كل يوم، يقرؤها من قائمة في الصفحة، ويبدأ أسبوعه كما تبدؤه لغة الصفحة.' }
  ] },
  { group: 'القوالب', en: 'Templates', pages: [
    { slug: 'login', title: 'تسجيل الدخول', en: 'Login template', icon: 'user',
      lead: 'صفحة دخول بخطوات: الهاتف، ثم كلمة المرور، ثم الرمز، في بطاقة تنزلق خطواتها، من أجزاء المكتبة وحدها.' },
    { slug: 'tpl-dashboard', title: 'لوحة التحكم', en: 'Dashboard template', icon: 'home', fresh: true,
      lead: 'واجهة التطبيق الأولى: أرقام اليوم وتغيرها، ورسمان، وأحدث السجلات، وآخر النشاط.' },
    { slug: 'tpl-tickets', title: 'صفحة قائمة', en: 'List page template', icon: 'inbox', fresh: true,
      lead: 'قائمة سجلات فيها بحث وتصفية وترتيب وتحديد جماعي وترقيم.' },
    { slug: 'tpl-order', title: 'صفحة تفاصيل', en: 'Detail page template', icon: 'cart', fresh: true,
      lead: 'سجل واحد بتفاصيله كلها: مساره وتعليقاته ومن يتولاه.' },
    { slug: 'tpl-settings', title: 'الإعدادات', en: 'Settings template', icon: 'cog', fresh: true,
      lead: 'إعدادات الحساب في علامات تبويب: ملف شخصي يحفظ نفسه، وإشعارات، وأمان.' },
    { slug: 'tpl-review', title: 'مراجعة بمعايير', en: 'Criteria review template', icon: 'file', fresh: true,
      lead: 'مستند وتقييمه جنبًا إلى جنب: معايير بمستويات ودرجات، وتقييم مقترح بمصادره، ومراجع يعدله.' },
    { slug: 'tpl-booking', title: 'نموذج بوقت محدود', en: 'Timed multi-step form template', icon: 'clock', fresh: true,
      lead: 'نموذج بخطوات محجوز لك وقتًا محدودًا، تؤجل من خطواته ما شئت للمراجعة، ويحفظ نفسه تلقائيًا.' },
    { slug: 'tpl-error', title: 'صفحة الخطأ', en: 'Error page template', icon: 'alert', fresh: true,
      lead: 'صفحة «غير موجودة» في وسط الشاشة، فيها بحث وطريق للعودة.' }
  ] },
  { group: 'الملحقات', en: 'Extras', pages: [
    { slug: 'navbar', level: 'advanced', title: 'شريط الموقع', en: 'Navbar', icon: 'compass',
      lead: 'شريط تنقل (Navbar) للمواقع لا للتطبيقات: جزيرة زجاجية تنطوي خلف زر على الهاتف.' },
    { slug: 'carousel', level: 'advanced', title: 'عرض الشرائح', en: 'Carousel', icon: 'slides',
      lead: 'عرض شرائح (Carousel) في صف تسحبه بإصبعك، وأزرار ونقاط وأسهم تتبع اتجاه القراءة، ولا يتحرك من تلقاء نفسه.' },
    { slug: 'colorpicker', level: 'advanced', title: 'منتقي الألوان', en: 'Color picker', icon: 'droplet',
      lead: 'حقل لون بمنتقٍ كامل، يخبرك قبل الحفظ هل يصلح اللون للنص، بتباينه على الأبيض وعلى الأسود.' },
    { slug: 'reveal', level: 'advanced', title: 'حركات الدخول', en: 'Entrance motion & scroll reveal', icon: 'sparkle',
      lead: 'أبناء حاوية يدخلون تباعًا حين تظهر على الشاشة (reveal)، وثلاثة كلاسات تمنح عنصرًا واحدًا حركة دخول.' }
  ] }
];

const PAGES = NAV.flatMap((g) => g.pages.map((p) => ({ ...p, group: g.group, groupEn: g.en })));

/* --------------------------------------------------------------------------
   Text helpers
   -------------------------------------------------------------------------- */

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attr = (s) => esc(s).replace(/"/g, '&quot;');

/* Strip the indentation the source happened to be written at, and the blank
   lines around it, so a listing starts at column zero. */
function dedent(src) {
  const lines = src.replace(/\t/g, '  ').split('\n');
  while (lines.length && !lines[0].trim()) lines.shift();
  while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
  const indent = Math.min(...lines.filter((l) => l.trim()).map((l) => l.match(/^ */)[0].length));
  return lines.map((l) => l.slice(indent)).join('\n');
}

/* --------------------------------------------------------------------------
   Highlighting, done once here so the pages ship no highlighter.
   Deliberately small: tags, attributes, strings and comments for markup; strings,
   comments, keywords and numbers for script. Good enough to read, and nothing a
   reader would mistake for a real parser.
   -------------------------------------------------------------------------- */

function hlHtml(src) {
  const re = /<!--[\s\S]*?-->|<\/?[a-zA-Z][\w-]*(?:\s+[^\s=>/]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?)*\s*\/?>/g;
  let out = '', last = 0, m;
  while ((m = re.exec(src))) {
    out += esc(src.slice(last, m.index));
    const tok = m[0];
    if (tok.startsWith('<!--')) {
      out += `<span class="hl-c">${esc(tok)}</span>`;
    } else {
      const head = tok.match(/^<\/?[a-zA-Z][\w-]*/)[0];
      const tail = tok.match(/\s*\/?>$/)[0];
      const body = tok.slice(head.length, tok.length - tail.length);
      out += `<span class="hl-t">${esc(head)}</span>`;
      out += body.replace(/([^\s=]+)(\s*=\s*)?("[^"]*"|'[^']*'|[^\s>]+)?|\s+/g, (all, name, eq, val) => {
        if (!name) return all;
        return `<span class="hl-a">${esc(name)}</span>${eq ? esc(eq) : ''}${val ? `<span class="hl-s">${esc(val)}</span>` : ''}`;
      });
      out += `<span class="hl-t">${esc(tail)}</span>`;
    }
    last = m.index + tok.length;
  }
  return out + esc(src.slice(last));
}

const JS_WORDS = /^(?:const|let|var|function|return|if|else|new|true|false|null|undefined|await|async|this|typeof|import|from|export)$/;

function hlScript(src, css) {
  const re = css
    ? /\/\*[\s\S]*?\*\/|"[^"]*"|'[^']*'|--[\w-]+|[\w-]+(?=\s*:)|#[0-9a-fA-F]{3,8}\b|\b\d+(?:\.\d+)?(?:px|rem|em|s|%)?/g
    : /\/\*[\s\S]*?\*\/|\/\/[^\n]*|`[^`]*`|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|\b[A-Za-z_$][\w$]*\b|\b\d+(?:\.\d+)?\b/g;
  let out = '', last = 0, m;
  while ((m = re.exec(src))) {
    const t = m[0];
    let cls = '';
    if (t.startsWith('/*') || t.startsWith('//')) cls = 'hl-c';
    else if (/^["'`]/.test(t)) cls = 'hl-s';
    else if (/^\d|^#/.test(t)) cls = 'hl-n';
    else if (css) cls = t.startsWith('--') ? 'hl-a' : 'hl-t';
    else if (JS_WORDS.test(t)) cls = 'hl-k';
    else if (t === 'Insiyab' || t === 'document' || t === 'window') cls = 'hl-t';
    out += esc(src.slice(last, m.index)) + (cls ? `<span class="${cls}">${esc(t)}</span>` : esc(t));
    last = m.index + t.length;
  }
  return out + esc(src.slice(last));
}

function listing(src, lang) {
  const code = dedent(src);
  const body = lang === 'html' ? hlHtml(code)
    : lang === 'js' ? hlScript(code, false)
    : lang === 'css' ? hlScript(code, true)
    : esc(code);
  return `<div class="dx-code" data-lang="${lang}"><button class="dx-copy" type="button" aria-label="نسخ الشيفرة" data-ins-tip>نسخ</button><pre dir="ltr"><code>${body}</code></pre></div>`;
}

/* In a listing, an inline icon is noise: its <use> points at this site's sprite,
   which is not something anyone is going to copy. Show that an icon goes there,
   not which one. */
function forListing(markup) {
  return markup.replace(/<svg class="ico"[^>]*>[\s\S]*?<\/svg>/g, '<svg>…</svg>');
}

const MODE_CLASS = { advanced: 'site-adv', simple: 'site-simple' };

// Wraps a data-level heading and its section in that mode's class; examples are masked so their headings are skipped.
function levels(html, file) {
  const kept = [];
  const src = html.replace(/<demo-(example|code)[\s\S]*?<\/demo-\1>/g, (m) => `\u0000${kept.push(m) - 1}\u0000`);
  const heads = [...src.matchAll(/<h([23])\b([^>]*)>/g)].map((m) => ({
    at: m.index, rank: +m[1], mode: (m[2].match(/\sdata-level="([^"]*)"/) || [])[1], id: (m[2].match(/\sid="([^"]+)"/) || [])[1]
  }));
  if (/\sdata-level\b/.test(src.replace(/<h[23]\b[^>]*>/g, ''))) problems.push(`${file}: data-level works on an <h2> or <h3> only.`);
  const ids = { advanced: new Set(), simple: new Set() };
  let out = '', last = 0;
  for (let i = 0; i < heads.length; i++) {
    const h = heads[i];
    if (!h.mode || h.at < last) continue;
    if (!MODE_CLASS[h.mode]) { problems.push(`${file}: data-level="${h.mode}" is not simple or advanced.`); continue; }
    let j = i + 1;
    while (j < heads.length && heads[j].rank > h.rank) j++;
    for (let k = i; k < j; k++) if (heads[k].id) ids[h.mode].add(heads[k].id);
    const end = j < heads.length ? heads[j].at : src.length;
    out += src.slice(last, h.at) + `<div class="${MODE_CLASS[h.mode]}">${src.slice(h.at, end).trimEnd()}</div>\n\n`;
    last = end;
  }
  out += src.slice(last);
  out = out.replace(/(<h[23]\b[^>]*?)\sdata-level="[^"]*"/g, '$1').replace(/\u0000(\d+)\u0000/g, (m, n) => kept[n]);
  return { html: out, ids };
}

const shows = (p, mode) => !p.level || p.level === mode;

function expand(html, file) {
  html = html.replace(/<demo-example([^>]*)>([\s\S]*?)<\/demo-example>/g, (all, attrs, inner) => {
    const cls = (attrs.match(/class="([^"]*)"/) || [])[1] || '';
    const noCode = /code="none"/.test(attrs);
    const view = `<div class="dx-view${cls ? ' ' + cls : ''}">${inner}</div>`;
    return `<figure class="dx${noCode ? ' dx--bare' : ''}">${view}${noCode ? '' : listing(forListing(inner), 'html')}</figure>`;
  });
  html = html.replace(/<demo-code(?:\s+lang="([a-z]+)")?>([\s\S]*?)<\/demo-code>/g, (all, lang, inner) => listing(inner, lang || 'html'));
  if (/<demo-(example|code)/.test(html)) problems.push(`${file}: an unclosed <demo-example> or <demo-code>.`);
  return html;
}

/* --------------------------------------------------------------------------
   The parts of the shell that change per page
   -------------------------------------------------------------------------- */

const icon = (name, cls = 'ico') => `<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;

function sidebar(current) {
  return NAV.map((g) => {
    const links = g.pages.map((p) => {
      const on = p.slug === current.slug;
      /* `fresh`: new or grown since the last review, flagged until it has been seen. */
      const badge = p.fresh ? '<span class="ins-shell-link-badge">جديد</span>' : '';
      const only = p.level && !on ? ` ${MODE_CLASS[p.level]}` : '';
      return `      <a class="ins-shell-link${on ? ' is-active' : ''}${only}" href="${p.slug}.html"${on ? ' aria-current="page"' : ''} data-keywords="${attr(p.lead ? `${p.en} ${p.lead}` : p.en)}">${icon(p.icon)}${p.title}${badge}</a>`;
    }).join('\n');
    const seen = (mode) => g.pages.some((p) => p.slug === current.slug || shows(p, mode));
    const hide = !seen('simple') ? ' site-adv' : !seen('advanced') ? ' site-simple' : '';
    return `      <div class="ins-shell-group${hide}">${g.group}</div>\n${links}`;
  }).join('\n\n');
}

/* The page's name is said once, in the top bar, where it is the page's <h1>. The
   home page has its own <h1> in the hero, so there the top bar only labels it. A
   page one step from the sidebar needs no breadcrumb, so the content opens with the
   page's one-line lead. */
function pageTitle(p) {
  return p.hero ? `<span class="ins-shell-title">${p.title}</span>` : `<h1 class="ins-shell-title">${p.title}</h1>`;
}

function pageHead(p) {
  return p.hero ? '' : `<p class="site-lead">${p.lead}</p>`;
}

/* "On this page": the page's own h2s and h3s, in the scrollspy plugin's contents
   list beside the content. Only worth it from three sections up. */
// One list per mode: the scrollspy would count a hidden heading as scrolled past.
function toc(html, ids) {
  const own = html.replace(/<figure class="dx[\s\S]*?<\/figure>/g, '');
  const heads = [...own.matchAll(/<h([23]) id="([^"]+)"[^>]*>([\s\S]*?)<\/h\1>/g)];
  const list = (hs, cls) => {
    if (hs.filter(([, level]) => level === '2').length < 3) return '';
    const links = hs.map(([, level, id, text]) =>
      `<a${level === '3' ? ' class="ins-toc-sub"' : ''} href="#${id}">${text.replace(/<[^>]+>/g, '').trim()}</a>`).join('');
    return `<nav class="ins-toc site-toc${cls}" data-ins-scrollspy aria-label="في هذه الصفحة"><div class="ins-toc-title">في هذه الصفحة</div>${links}</nav>`;
  };
  if (!ids.advanced.size && !ids.simple.size) return list(heads, '');
  const minus = (set) => heads.filter(([, , id]) => !set.has(id));
  return list(minus(ids.simple), ' site-adv') + list(minus(ids.advanced), ' site-simple');
}

// Each mode's pager skips the pages the other mode alone shows, so it is a second nav when that changes a neighbour.
function pager(i) {
  const card = (p, dir) => p
    ? `<a class="site-pager-link site-pager-link--${dir}" href="${p.slug}.html"><span class="site-pager-dir">${dir === 'prev' ? 'السابق' : 'التالي'}</span><span class="site-pager-title">${p.title}</span></a>`
    : '<span></span>';
  const nav = (prev, next, cls) => `<nav class="site-pager${cls}" aria-label="التنقل بين الصفحات">${card(prev, 'prev')}${card(next, 'next')}</nav>`;
  const near = (mode) => [PAGES.slice(0, i).reverse().find((p) => shows(p, mode)), PAGES.slice(i + 1).find((p) => shows(p, mode))];
  const [aPrev, aNext] = near('advanced'), [sPrev, sNext] = near('simple');
  if (aPrev === sPrev && aNext === sNext) return nav(aPrev, aNext, '');
  return nav(aPrev, aNext, ' site-adv') + nav(sPrev, sNext, ' site-simple');
}

/* --------------------------------------------------------------------------
   Checks — cheap, and each one is a broken page nobody would notice for a while
   -------------------------------------------------------------------------- */

const problems = [];

function verifyPage(p, html, slugs, shared) {
  for (const [, href] of html.matchAll(/href="([a-z0-9-]+)\.html(?:#[^"]*)?"/g)) {
    if (!slugs.has(href)) problems.push(`pages/${p.slug}.html links to ${href}.html, which is not in NAV.`);
  }
  const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  const dup = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dup.length) problems.push(`pages/${p.slug}.html: duplicate ids ${[...new Set(dup)].join(', ')}`);
  for (const [, id] of html.matchAll(/href="#([^"]+)"/g)) {
    /* Icons included: a misspelt <use href="#i-…"> draws nothing and says nothing. */
    if (!ids.includes(id) && !shared.has(id)) problems.push(`pages/${p.slug}.html: #${id} points at nothing on the page or in the layout.`);
  }
  /* The page's own h2s — an h2 inside an example is the example's business. */
  const own = html.replace(/<figure class="dx[\s\S]*?<\/figure>/g, '');
  for (const [tag] of own.matchAll(/<h2(?![^>]*\bid=)[^>]*>/g)) {
    problems.push(`pages/${p.slug}.html: ${tag} has no id, so it cannot be linked or listed.`);
  }
}

/* -------------------------------------------------------------------------- */

export async function buildSite({ check = false, version = '' } = {}) {
  problems.length = 0;
  const layout = await readFile(join(SRC, 'layout.html'), 'utf8');
  const slugs = new Set(PAGES.map((p) => p.slug));
  /* Ids every page has, from the layout: the icon sprite, the sidebar, search. */
  const shared = new Set([...layout.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));

  const have = (await readdir(join(SRC, 'pages'))).filter((f) => f.endsWith('.html')).map((f) => f.slice(0, -5));
  for (const s of have) if (!slugs.has(s)) problems.push(`pages/${s}.html exists but is not in NAV, so nothing links to it.`);

  const out = [];
  for (let i = 0; i < PAGES.length; i++) {
    const p = PAGES[i];
    let src;
    try { src = await readFile(join(SRC, 'pages', `${p.slug}.html`), 'utf8'); }
    catch { problems.push(`pages/${p.slug}.html is listed in NAV and missing.`); continue; }

    if (p.level && !MODE_CLASS[p.level]) problems.push(`NAV: ${p.slug} has level '${p.level}', not simple or advanced.`);
    const { html: leveled, ids } = levels(src, `pages/${p.slug}.html`);
    if (p.level && (ids.advanced.size || ids.simple.size)) problems.push(`pages/${p.slug}.html: the page has a level of its own, so data-level on its sections is not allowed.`);
    const content = expand(leveled, `pages/${p.slug}.html`);
    verifyPage(p, content, slugs, shared);

    const fill = {
      SLUG: p.slug,
      TITLE: pageTitle(p),
      DOC_TITLE: p.hero ? 'انسياب · مكتبة واجهات تليق بالعربية' : `${p.title} · انسياب`,
      DESCRIPTION: attr(p.lead || 'مكتبة واجهات تليق بالعربية، يصفو زجاجها وينساب خطها.'),
      VERSION: version,
      SIDEBAR: sidebar(p),
      HEAD: pageHead(p),
      TOC: toc(content, ids),
      CONTENT: content.trim(),
      PAGER: pager(i),
      BODY_CLASS: p.hero ? 'site-home' : 'site-doc'
    };
    const html = layout
      .replace('<!doctype html>', `<!doctype html>\n${MARK}${p.slug}.html — edit that, not this. -->`)
      .replace(/\{\{([A-Z_]+)\}\}/g, (all, key) => {
        if (!(key in fill)) { problems.push(`layout.html: unknown slot {{${key}}}`); return all; }
        return fill[key];
      });
    out.push([join(DIR, `${p.slug}.html`), html]);
  }

  if (problems.length) return { problems: [...problems], pages: out.length };
  if (check) return { problems: [], pages: out.length };

  /* A page dropped from NAV leaves its old output behind; remove anything this
     build generated before and did not generate now. Only files carrying the
     marker — a hand-written file in demo/ is never touched. */
  const written = new Set(out.map(([path]) => path));
  for (const f of await readdir(DIR)) {
    const path = join(DIR, f);
    if (!f.endsWith('.html') || written.has(path)) continue;
    if ((await readFile(path, 'utf8')).includes(MARK)) await unlink(path);
  }
  for (const [path, html] of out) await writeFile(path, html, 'utf8');
  return { problems: [], pages: out.length };
}
