/* ==========================================================================
   Insiyab · the demo site
   ==========================================================================

   The demo is a documentation site: one page per topic, static HTML, the same
   shell on every page. It is generated rather than hand-written because the
   shell — sidebar, top bar, search, pager — is identical on ~40 pages, and
   forty hand-kept copies of one sidebar are forty chances to forget a link.

   Sources live in demo/src:

     site.mjs          this file: the page list (the one place a page is added)
     layout.html       the shell every page is poured into
     pages/<slug>.html one fragment per page — just its content

   Output is demo/<slug>.html, plain files that need no script to read. They are
   committed, so the demo works from a static host or a checkout with no build.

   Two custom tags are expanded at build time, so a page never repeats itself:

     <demo-example class="row">…live markup…</demo-example>
         renders the markup, and prints the same markup, highlighted, under it.
         `code="none"` renders without the listing.

     <demo-code lang="html|js|css|sh">…source…</demo-code>
         a listing on its own. Write the source as-is; it is escaped here.

   Run through `node build.mjs`, which calls buildSite() after the library.
   ========================================================================== */

import { readFile, writeFile, readdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';

const DIR = 'demo';
const SRC = 'demo/src';
const MARK = '<!-- generated by build.mjs from demo/src/pages/';

/* --------------------------------------------------------------------------
   The page list. Order here is order in the sidebar and in the pager.
   `en` and `lead` are the search's keywords, carried on each sidebar link:
   `en` so an English query ("button") finds the page, the lead so a singular
   ("جدول") finds a page named in the plural ("الجداول").
   -------------------------------------------------------------------------- */

export const NAV = [
  { group: 'البداية', en: 'Getting started', pages: [
    { slug: 'index', title: 'مقدّمة', en: 'Introduction', icon: 'home', hero: true },
    { slug: 'start', title: 'البدء السريع', en: 'Quick start', icon: 'rocket',
      lead: 'ملفّان ومجلّد خطوط، ولا شيء غيرها. من الصفر إلى صفحة كاملة في دقيقة.' },
    { slug: 'javascript', title: 'الجافاسكربت', en: 'JavaScript', icon: 'code',
      lead: 'السمات أوّلًا، والواجهة البرمجية مخرج طوارئ. كلّ ما يتحرّك في المكتبة يعمل بسمة في الشيفرة، دون سطر جافاسكربت منك.' },
    { slug: 'faq', title: 'أسئلة شائعة', en: 'FAQ', icon: 'help',
      lead: 'ما يسأل عنه الناس قبل أن يعتمدوا المكتبة، بإجابات قصيرة.' }
  ] },
  { group: 'التخصيص', en: 'Customize', pages: [
    { slug: 'color', title: 'اللون والهوية', en: 'Color', icon: 'palette',
      lead: 'لون واحد، وكلّ ما عداه مشتقّ منه: التدرّج، والظلال، وحلقات التركيز، وخلفية الصفحة.' },
    { slug: 'dark', title: 'الوضع الداكن', en: 'Color modes', icon: 'moon',
      lead: 'لوحة ثانية صُمّمت لذاتها، لا قلبٌ للأولى. تتبع النظام افتراضيًا، ويُحفظ اختيار المستخدم.' },
    { slug: 'rtl', title: 'العربية والاتجاه', en: 'RTL', icon: 'languages',
      lead: 'من اليمين إلى اليسار افتراضًا أصيلًا لا إضافة: خصائص منطقية في كلّ مكان، ولا ملفّ انعكاس.' },
    { slug: 'motion', title: 'الحركة', en: 'Motion', icon: 'sparkle',
      lead: 'منحنى واحد، ودخول أبطأ من الخروج، ولا شيء يتكرّر إلى الأبد.' }
  ] },
  { group: 'التخطيط', en: 'Layout', pages: [
    { slug: 'shell', title: 'هيكل التطبيق', en: 'App shell', icon: 'layout',
      lead: 'شريط جانبي زجاجي وشريط علوي من جزر عائمة. هذه الصفحة نفسها مبنيّة به.' },
    { slug: 'grid', title: 'الشبكة', en: 'Grid', icon: 'grid',
      lead: 'أعمدة تنهار وحدها عند الشاشات الضيّقة، فلا أصناف لكلّ مقاس.' },
    { slug: 'spacing', title: 'المسافات والترتيب', en: 'Spacing & stacks', icon: 'sliders',
      lead: 'سلّم واحد، الخطوة فيه ٤ بكسل، وجهات منطقية لا يمين ولا يسار.' }
  ] },
  { group: 'المحتوى', en: 'Content', pages: [
    { slug: 'typography', title: 'الطباعة', en: 'Typography', icon: 'type',
      lead: 'ثلاثة خطوط مستضافة محليًا ومقسّمة حسب النطاق، وسلّم عناوين، ونصّ طويل محصور في صنفه.' },
    { slug: 'surfaces', title: 'الأسطح والألواح', en: 'Surfaces & panels', icon: 'layers',
      lead: 'الزجاج المصنفر بطبقاته الأربع، وما يُبنى عليه: البطاقة واللوح.' },
    { slug: 'tables', title: 'الجداول', en: 'Tables', icon: 'table',
      lead: 'جدول بيانات يقرأ الأرقام بخطّها، ويتمرّر أفقيًا داخل حاويته لا في الصفحة.' }
  ] },
  { group: 'النماذج', en: 'Forms', pages: [
    { slug: 'inputs', title: 'الحقول', en: 'Form controls', icon: 'edit',
      lead: 'حقل النصّ والقائمة والمنطقة النصّية، بالمقاسات الثلاثة وبالتسمية والتلميح.' },
    { slug: 'checks', title: 'الاختيار والمفاتيح', en: 'Checks & switches', icon: 'check-square',
      lead: 'مربّعات ودوائر ومفاتيح وبطاقات اختيار، كلّها عناصر إدخال حقيقية تحت التصميم.' },
    { slug: 'input-group', title: 'مجموعات الحقول', en: 'Input group', icon: 'link',
      lead: 'حقل وملحقاته في قطعة واحدة: وحدة، أو بادئة، أو زرّ، أو إظهار كلمة المرور.' },
    { slug: 'pickers', title: 'المنتقيات', en: 'Pickers', icon: 'calendar',
      lead: 'الإكمال التلقائي والتاريخ والمنزلق والعدّاد — أدوات إدخال يحتاجها كلّ نموذج جادّ.' },
    { slug: 'validation', title: 'التحقّق', en: 'Validation', icon: 'shield',
      lead: 'تحقّق المتصفّح نفسه، برسائل داخل الحقل بدل الفقاعة، ودون مكتبة تحقّق.' }
  ] },
  { group: 'المكوّنات', en: 'Components', pages: [
    { slug: 'buttons', title: 'الأزرار', en: 'Buttons', icon: 'pointer',
      lead: 'الألوان والأنماط والمقاسات، وأزرار التبديل والمجموعات، وزرّ الإغلاق.' },
    { slug: 'accordion', title: 'الأكورديون', en: 'Accordion', icon: 'chevrons',
      lead: 'أقسام قابلة للطيّ مبنيّة على عنصر details نفسه، فتعمل بلا جافاسكربت.' },
    { slug: 'tabs', title: 'الألسنة', en: 'Tabs', icon: 'tabs',
      lead: 'ألسنة تبدّل الألواح، بالأسهم وبالنقر، وبشكلين: الشريط والمقسّم.' },
    { slug: 'stats', title: 'البطاقات الإحصائية', en: 'Stat tiles', icon: 'chart',
      lead: 'رقم ومعناه ورقاقة أيقونة، بستّ نبرات وثلاثة مقاسات.' },
    { slug: 'loading', title: 'التحميل والفراغ', en: 'Loading & empty', icon: 'loader',
      lead: 'هيكل التحميل والدوّارة والحالة الفارغة — ما يراه المستخدم قبل البيانات وبدلها.' },
    { slug: 'progress', title: 'التقدّم', en: 'Progress', icon: 'gauge',
      lead: 'شريط تقدّم على عنصر progress الأصلي، وحلقة للنسب المئوية.' },
    { slug: 'tooltips', title: 'التلميحات', en: 'Tooltips', icon: 'message',
      lead: 'تلميح واحد للصفحة كلّها في الطبقة العليا، بسمة واحدة على العنصر.' },
    { slug: 'alerts', title: 'التنبيهات', en: 'Alerts', icon: 'alert',
      lead: 'رسالة ثابتة في الصفحة بأربع نبرات، قابلة للإغلاق.' },
    { slug: 'dialog', title: 'الحوار', en: 'Dialog', icon: 'window',
      lead: 'عنصر dialog الأصلي: الطبقة العليا وحبس التركيز والإغلاق بـ Esc، كلّها من المتصفّح.' },
    { slug: 'drawer', title: 'الدرج', en: 'Drawer', icon: 'sidebar',
      lead: 'الحوار نفسه ملتصقًا بحافة: البداية أو النهاية أو الأسفل.' },
    { slug: 'toasts', title: 'الرسائل الطائرة', en: 'Toasts', icon: 'bell',
      lead: 'إشعار عابر يظهر ويختفي وحده، بسمة على زرّ أو بسطر جافاسكربت.' },
    { slug: 'badges', title: 'الشارات والأرقام', en: 'Badges & numbers', icon: 'tag',
      lead: 'شارات الحالة وشارات العدّ والصور الرمزية، والمبالغ والأرقام في سطر عربي.' },
    { slug: 'list', title: 'القوائم', en: 'List group', icon: 'list',
      lead: 'صفوف متتالية بصورة ونصّين ونهاية، ثابتة أو قابلة للنقر.' },
    { slug: 'dropdown', title: 'القوائم المنبثقة', en: 'Dropdowns', icon: 'menu-down',
      lead: 'قائمة على عنصر details، بالأسهم والإغلاق بـ Esc وعناصر قابلة للتأشير.' },
    { slug: 'steps', title: 'المعالج', en: 'Steps & wizard', icon: 'steps',
      lead: 'نموذج مقسّم إلى خطوات، يتحقّق من كلّ خطوة قبل أن ينتقل منها.' },
    { slug: 'pagination', title: 'ترقيم الصفحات', en: 'Pagination', icon: 'pages',
      lead: 'روابط صفحات حقيقية بأسهم تتبع اتجاه النصّ.' },
    { slug: 'page-head', title: 'رأس الصفحة والمسار', en: 'Page header & breadcrumb', icon: 'route',
      lead: 'عنوان الصفحة وسطر تحته وإجراءاتها، ومسار التنقّل فوقها.' },
    { slug: 'navbar', title: 'شريط الموقع', en: 'Navbar', icon: 'compass',
      lead: 'شريط تنقّل لموقع لا لتطبيق: جزيرة زجاجية تنطوي خلف زرّ على الهاتف.' }
  ] },
  { group: 'الأدوات', en: 'Utilities', pages: [
    { slug: 'utilities', title: 'الأدوات المساعدة', en: 'Utilities', icon: 'wrench',
      lead: 'أصناف صغيرة للنصّ والمرونة والإظهار، تُحمَّل بعد كلّ المكوّنات فتغلبها بلا !important.' }
  ] },
  { group: 'الإضافات', en: 'Plugins', pages: [
    { slug: 'hijri', title: 'التقويم الهجري', en: 'Hijri calendar', icon: 'moon',
      lead: 'حقل التاريخ بالتقويم الهجري — أمّ القرى أو الحسابي — ومفتاح إلى الميلادي. والخادم يستلم التاريخ الميلادي كما هو.' },
    { slug: 'palette', title: 'لوحة الأوامر', en: 'Command palette', icon: 'search',
      lead: 'بحث واحد عن كلّ صفحة وكلّ أمر، يُفتح بـ Ctrl+K. عناصره روابط الصفحة وأزرارها كما هي، ويجمع روابط القائمة الجانبية بنفسه.' },
    { slug: 'otp', title: 'رمز التحقق', en: 'One-time code', icon: 'lock',
      lead: 'حقل الرمز المرسل برسالة، مربّع لكلّ رقم — وهو حقل واحد حقيقيّ، فيُلصق فيه ويقترحه الهاتف ويقرؤه قارئ الشاشة.' },
    { slug: 'phone', title: 'رقم الهاتف', en: 'Phone number', icon: 'phone',
      lead: 'حقل الهاتف بدولته: الرقم مكتوب كما يُكتب في بلده، ويصل إلى الخادم بصيغة E.164 الدولية.' },
    { slug: 'file', title: 'رفع الملفات', en: 'File upload', icon: 'upload',
      lead: 'منطقة إفلات وقائمة بالملفّات، والملفّات باقية في حقل الملفّات الحقيقيّ فتُرسل مع النموذج كما هي.' },
    { slug: 'scrollspy', title: 'تتبع القراءة', en: 'Scrollspy', icon: 'list',
      lead: 'قائمة محتويات تتبع القارئ: رابط القسم الذي يُقرأ معلَّم، في الصفحة أو في صندوق بتمريره الخاصّ.' },
    { slug: 'timeline', title: 'الخط الزمني', en: 'Timeline', icon: 'clock',
      lead: 'ما حدث بترتيبه: مسار طلب، أو نشاط حساب، أو تاريخ ملفّ. ومعه أوقات نسبية تُكتب كما تُقال.' },
    { slug: 'tree', title: 'الشجرة', en: 'Tree', icon: 'folder',
      lead: 'قوائم متداخلة شجرةً: ملفّات أو تصنيفات أو صلاحيات، بالأسهم كشجرة ملفّات، وبمربّعات متسلسلة.' },
    { slug: 'colorpicker', title: 'منتقي الألوان', en: 'Color picker', icon: 'droplet',
      lead: 'حقل لون بمنتقٍ كامل، يقول قبل الحفظ هل يصلح اللون لنصّ: تباينه على الأبيض وعلى الأسود.' }
  ] }
];

const PAGES = NAV.flatMap((g) => g.pages.map((p) => ({ ...p, group: g.group, groupEn: g.en })));

/* --------------------------------------------------------------------------
   Text helpers
   -------------------------------------------------------------------------- */

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attr = (s) => esc(s).replace(/"/g, '&quot;');

/* Strip the indentation the source happened to be written at, and the blank
   lines around it, so a listing starts at column zero. */
function dedent(src) {
  const lines = src.replace(/\t/g, '  ').split('\n');
  while (lines.length && !lines[0].trim()) lines.shift();
  while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
  const indent = Math.min(...lines.filter((l) => l.trim()).map((l) => l.match(/^ */)[0].length));
  return lines.map((l) => l.slice(indent)).join('\n');
}

/* --------------------------------------------------------------------------
   Highlighting, done once here so the pages ship no highlighter.
   Deliberately small: tags, attributes, strings and comments for markup; strings,
   comments, keywords and numbers for script. Good enough to read, and nothing a
   reader would mistake for a real parser.
   -------------------------------------------------------------------------- */

function hlHtml(src) {
  const re = /<!--[\s\S]*?-->|<\/?[a-zA-Z][\w-]*(?:\s+[^\s=>/]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?)*\s*\/?>/g;
  let out = '', last = 0, m;
  while ((m = re.exec(src))) {
    out += esc(src.slice(last, m.index));
    const tok = m[0];
    if (tok.startsWith('<!--')) {
      out += `<span class="hl-c">${esc(tok)}</span>`;
    } else {
      const head = tok.match(/^<\/?[a-zA-Z][\w-]*/)[0];
      const tail = tok.match(/\s*\/?>$/)[0];
      const body = tok.slice(head.length, tok.length - tail.length);
      out += `<span class="hl-t">${esc(head)}</span>`;
      out += body.replace(/([^\s=]+)(\s*=\s*)?("[^"]*"|'[^']*'|[^\s>]+)?|\s+/g, (all, name, eq, val) => {
        if (!name) return all;
        return `<span class="hl-a">${esc(name)}</span>${eq ? esc(eq) : ''}${val ? `<span class="hl-s">${esc(val)}</span>` : ''}`;
      });
      out += `<span class="hl-t">${esc(tail)}</span>`;
    }
    last = m.index + tok.length;
  }
  return out + esc(src.slice(last));
}

const JS_WORDS = /^(?:const|let|var|function|return|if|else|new|true|false|null|undefined|await|async|this|typeof|import|from|export)$/;

function hlScript(src, css) {
  const re = css
    ? /\/\*[\s\S]*?\*\/|"[^"]*"|'[^']*'|--[\w-]+|[\w-]+(?=\s*:)|#[0-9a-fA-F]{3,8}\b|\b\d+(?:\.\d+)?(?:px|rem|em|s|%)?/g
    : /\/\*[\s\S]*?\*\/|\/\/[^\n]*|`[^`]*`|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|\b[A-Za-z_$][\w$]*\b|\b\d+(?:\.\d+)?\b/g;
  let out = '', last = 0, m;
  while ((m = re.exec(src))) {
    const t = m[0];
    let cls = '';
    if (t.startsWith('/*') || t.startsWith('//')) cls = 'hl-c';
    else if (/^["'`]/.test(t)) cls = 'hl-s';
    else if (/^\d|^#/.test(t)) cls = 'hl-n';
    else if (css) cls = t.startsWith('--') ? 'hl-a' : 'hl-t';
    else if (JS_WORDS.test(t)) cls = 'hl-k';
    else if (t === 'Insiyab' || t === 'document' || t === 'window') cls = 'hl-t';
    out += esc(src.slice(last, m.index)) + (cls ? `<span class="${cls}">${esc(t)}</span>` : esc(t));
    last = m.index + t.length;
  }
  return out + esc(src.slice(last));
}

function listing(src, lang) {
  const code = dedent(src);
  const body = lang === 'html' ? hlHtml(code)
    : lang === 'js' ? hlScript(code, false)
    : lang === 'css' ? hlScript(code, true)
    : esc(code);
  return `<div class="dx-code" data-lang="${lang}"><button class="dx-copy" type="button" aria-label="نسخ الشيفرة" data-ins-tip>نسخ</button><pre dir="ltr"><code>${body}</code></pre></div>`;
}

/* In a listing, an inline icon is noise: its <use> points at this site's sprite,
   which is not something anyone is going to copy. Show that an icon goes there,
   not which one. */
function forListing(markup) {
  return markup.replace(/<svg class="ico"[^>]*>[\s\S]*?<\/svg>/g, '<svg>…</svg>');
}

function expand(html, file) {
  html = html.replace(/<demo-example([^>]*)>([\s\S]*?)<\/demo-example>/g, (all, attrs, inner) => {
    const cls = (attrs.match(/class="([^"]*)"/) || [])[1] || '';
    const noCode = /code="none"/.test(attrs);
    const view = `<div class="dx-view${cls ? ' ' + cls : ''}">${inner}</div>`;
    return `<figure class="dx${noCode ? ' dx--bare' : ''}">${view}${noCode ? '' : listing(forListing(inner), 'html')}</figure>`;
  });
  html = html.replace(/<demo-code(?:\s+lang="([a-z]+)")?>([\s\S]*?)<\/demo-code>/g, (all, lang, inner) => listing(inner, lang || 'html'));
  if (/<demo-(example|code)/.test(html)) problems.push(`${file}: an unclosed <demo-example> or <demo-code>.`);
  return html;
}

/* --------------------------------------------------------------------------
   The parts of the shell that change per page
   -------------------------------------------------------------------------- */

const icon = (name, cls = 'ico') => `<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;

function sidebar(current) {
  return NAV.map((g) => {
    const links = g.pages.map((p) => {
      const on = p.slug === current.slug;
      return `      <a class="ins-shell-link${on ? ' is-active' : ''}" href="${p.slug}.html"${on ? ' aria-current="page"' : ''} data-keywords="${attr(p.lead ? `${p.en} ${p.lead}` : p.en)}">${icon(p.icon)}${p.title}</a>`;
    }).join('\n');
    return `      <div class="ins-shell-group">${g.group}</div>\n${links}`;
  }).join('\n\n');
}

function pageHead(p) {
  if (p.hero) return '';
  return `<header class="ins-page-head">
          <nav class="ins-breadcrumb" aria-label="مسار التنقّل">
            <ol>
              <li><a href="index.html">انسياب</a></li>
              <li><span>${p.group}</span></li>
              <li><span aria-current="page">${p.title}</span></li>
            </ol>
          </nav>
          <div class="ins-page-head-text">
            <span class="ins-eyebrow">${p.en}</span>
            <h1 class="ins-page-title">${p.title}</h1>
            <p class="ins-page-sub site-lead">${p.lead}</p>
          </div>
        </header>`;
}

/* "On this page": the page's own h2s, as chips. Only worth it from three up. */
function toc(html) {
  const heads = [...html.matchAll(/<h2 id="([^"]+)"[^>]*>([\s\S]*?)<\/h2>/g)];
  if (heads.length < 3) return '';
  const chips = heads.map(([, id, text]) => `<a href="#${id}">${text.replace(/<[^>]+>/g, '').trim()}</a>`).join('');
  return `<nav class="site-toc" aria-label="في هذه الصفحة"><span class="site-toc-label">في هذه الصفحة</span>${chips}</nav>`;
}

function pager(i) {
  const prev = PAGES[i - 1], next = PAGES[i + 1];
  const card = (p, dir) => p
    ? `<a class="site-pager-link site-pager-link--${dir}" href="${p.slug}.html"><span class="site-pager-dir">${dir === 'prev' ? 'السابق' : 'التالي'}</span><span class="site-pager-title">${p.title}</span></a>`
    : '<span></span>';
  return `<nav class="site-pager" aria-label="التنقّل بين الصفحات">${card(prev, 'prev')}${card(next, 'next')}</nav>`;
}

/* --------------------------------------------------------------------------
   Checks — cheap, and each one is a broken page nobody would notice for a while
   -------------------------------------------------------------------------- */

const problems = [];

function verifyPage(p, html, slugs, shared) {
  for (const [, href] of html.matchAll(/href="([a-z0-9-]+)\.html(?:#[^"]*)?"/g)) {
    if (!slugs.has(href)) problems.push(`pages/${p.slug}.html links to ${href}.html, which is not in NAV.`);
  }
  const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  const dup = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dup.length) problems.push(`pages/${p.slug}.html: duplicate ids ${[...new Set(dup)].join(', ')}`);
  for (const [, id] of html.matchAll(/href="#([^"]+)"/g)) {
    /* Icons included: a misspelt <use href="#i-…"> draws nothing and says nothing. */
    if (!ids.includes(id) && !shared.has(id)) problems.push(`pages/${p.slug}.html: #${id} points at nothing on the page or in the layout.`);
  }
  /* The page's own h2s — an h2 inside an example is the example's business. */
  const own = html.replace(/<figure class="dx[\s\S]*?<\/figure>/g, '');
  for (const [tag] of own.matchAll(/<h2(?![^>]*\bid=)[^>]*>/g)) {
    problems.push(`pages/${p.slug}.html: ${tag} has no id, so it cannot be linked or listed.`);
  }
}

/* -------------------------------------------------------------------------- */

export async function buildSite({ check = false, version = '' } = {}) {
  problems.length = 0;
  const layout = await readFile(join(SRC, 'layout.html'), 'utf8');
  const slugs = new Set(PAGES.map((p) => p.slug));
  /* Ids every page has, from the layout: the icon sprite, the sidebar, search. */
  const shared = new Set([...layout.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));

  const have = (await readdir(join(SRC, 'pages'))).filter((f) => f.endsWith('.html')).map((f) => f.slice(0, -5));
  for (const s of have) if (!slugs.has(s)) problems.push(`pages/${s}.html exists but is not in NAV, so nothing links to it.`);

  const out = [];
  for (let i = 0; i < PAGES.length; i++) {
    const p = PAGES[i];
    let src;
    try { src = await readFile(join(SRC, 'pages', `${p.slug}.html`), 'utf8'); }
    catch { problems.push(`pages/${p.slug}.html is listed in NAV and missing.`); continue; }

    const content = expand(src, `pages/${p.slug}.html`);
    verifyPage(p, content, slugs, shared);

    const fill = {
      SLUG: p.slug,
      TITLE: p.title,
      DOC_TITLE: p.hero ? 'انسياب · مكتبة واجهات عربية أولًا' : `${p.title} · انسياب`,
      DESCRIPTION: attr(p.lead || 'مكتبة واجهات بتصميم الزجاج المصنفر، عربية أولًا. ملفّان، بلا أدوات بناء.'),
      VERSION: version,
      SIDEBAR: sidebar(p),
      HEAD: pageHead(p),
      TOC: toc(content),
      CONTENT: content.trim(),
      PAGER: pager(i),
      BODY_CLASS: p.hero ? 'site-home' : 'site-doc'
    };
    const html = layout
      .replace('<!doctype html>', `<!doctype html>\n${MARK}${p.slug}.html — edit that, not this. -->`)
      .replace(/\{\{([A-Z_]+)\}\}/g, (all, key) => {
        if (!(key in fill)) { problems.push(`layout.html: unknown slot {{${key}}}`); return all; }
        return fill[key];
      });
    out.push([join(DIR, `${p.slug}.html`), html]);
  }

  if (problems.length) return { problems: [...problems], pages: out.length };
  if (check) return { problems: [], pages: out.length };

  /* A page dropped from NAV leaves its old output behind; remove anything this
     build generated before and did not generate now. Only files carrying the
     marker — a hand-written file in demo/ is never touched. */
  const written = new Set(out.map(([path]) => path));
  for (const f of await readdir(DIR)) {
    const path = join(DIR, f);
    if (!f.endsWith('.html') || written.has(path)) continue;
    if ((await readFile(path, 'utf8')).includes(MARK)) await unlink(path);
  }
  for (const [path, html] of out) await writeFile(path, html, 'utf8');
  return { problems: [], pages: out.length };
}
